### ISSUE TITLE
Shared news articles - Issue #6

### ISSUE THREAD

**Issue by cfitzgerald9** [NewForce-at-Mountwest/nutshell-team-knotw-se#7]
# Story
As a user, I should be able to list interesting news articles on my dashboard

# Acceptance Criteria
**Given** a user wants to record a news article on their dashboard
**When** the user performs a gesture on a `New Article` affordance
**Then** a form should be presented to the user in which the following information can be entered

1. News title
2. Synopsis
3. URL

**Given** a user has entered in all field values for storing a new article
**When** the user performs a gesture on the `Save Article` affordance
**Then** the article should be saved in the database, and assigned to the user
**And** should have a property of the current timestamp

**Given** a user has saved news articles
**When** the user visits their dashboard
**Then** the news articles should be presented in the `News` components, sorted by date in descending order
**And** each article should have an affordance to delete the news article

**Given** a user wants to remove a previously stored news article
**When** the user performs a gesture on the delete affordance
**Then** the article should be deleted

**Given** a user wants to change the details of a news article
**When** the user performs a gesture to edit the article
**Then** the user should be presented with a form that has the news article details pre-filled into the fields
**And** there should be an affordance to save the new details

**Comment by joeywellman** [comment]
**Shared News Article Completions (e.g. CRUD):**
- Added An Article (News) Component that Displays an Article's (News) Article ID, Title, Time, Synopsis, and URL.
- Added An Article Collection Component that Loads Existing (News) Articles from Storage and Saves New Ones.
- Component Added to Activate Delete Button(s) to Respond to 'Click' Events.
- Component Added to Activate the Edit Button(s) to Respond to 'Click' Events.
- Included a News Form Component that, when Populated (Filled Out) and a Submit (Button Pressed), Adds a New Article to 'Storage'.
- Included An Article List Component that Displays ALL News Articles.
-- Article List Built to Include Moment JavaScript Functionality to Sort Articles ("articles.sort((left, right)") in Reverse-Chronological / Descending Order ("right.time.diff(left.time)").
- Incorporated a Build Article Object Component to Create A Form that Should Be Presented to the User, which Includes Aforementioned Objects (Title, Time, Synopsis, and URL).
- Finalized an Save / Edit Article Handler that Handles User Inputs.
- Created a Component to Load the Articles 'Page', After Login.
- Omitted Date Collection from User Input and Replaced with Time [Value]
-- Method JavaScript Utilized to Parse, Validate, Manipulate, and Display Dates and Times in JavaScript / Store to Database / Sort Articles by Completion Date(s).

**Shared News Article Acceptance Criteria:**
- Form Presented Allows User to Enter Information:
-- News title
-- Synopsis
-- URL
- Entered Field Values Allow for Storing of New Articles
-- `Save Article` Affordance(s) Allow Saving to Database, and Assignment to User
-- Saved Articles have a Property of the Current Timestamp ("time")
-- 'Posted' News Articles presented in the `News` (Articles) Component are Sorted by Date in Descending Order
-- Each News Article Posted can be Deleted
-- Each News Article Posted can be Edited
-- Each News Article Selected for Editing Presents with a Form that has the News Article Details Pre-Populated into Fields, along with Affordance(s) to Save New Details
